import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const seedDemoData = mutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    // Demo e-commerce links
    const demoLinks = [
      {
        url: "https://shopee.sg/product-1",
        title: "Wireless Bluetooth Earbuds Pro Max",
        description: "Premium sound quality with active noise cancellation",
        image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop",
        price: "89.90",
        originalPrice: "129.90",
        currency: "$",
        platform: "shopee",
        userId: "user123",
        isPublic: true,
        bookmarkCount: 42,
        viewCount: 350,
      },
      {
        url: "https://lazada.com/product-2",
        title: "Smart Watch Series 8 GPS + Cellular",
        description: "Track your health and stay connected",
        image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
        price: "299",
        originalPrice: "399",
        currency: "$",
        platform: "lazada",
        userId: "user456",
        isPublic: true,
        bookmarkCount: 28,
        viewCount: 215,
      },
      {
        url: "https://shop.tiktok.com/product-3",
        title: "Portable Mini Projector 4K",
        description: "Cinema experience anywhere",
        image: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=400&h=400&fit=crop",
        price: "179.99",
        originalPrice: "249.99",
        currency: "$",
        platform: "tiktok",
        userId: "user789",
        isPublic: true,
        bookmarkCount: 56,
        viewCount: 480,
      },
      {
        url: "https://shopee.sg/product-4",
        title: "Gaming Mechanical Keyboard RGB",
        description: "Professional gaming keyboard with customizable RGB lighting",
        image: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400&h=400&fit=crop",
        price: "69.90",
        originalPrice: "99.90",
        currency: "$",
        platform: "shopee",
        userId: "user123",
        isPublic: true,
        bookmarkCount: 35,
        viewCount: 290,
      },
      {
        url: "https://lazada.com/product-5",
        title: "Ergonomic Office Chair",
        description: "Premium comfort for long working hours",
        image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400&h=400&fit=crop",
        price: "189",
        originalPrice: "289",
        currency: "$",
        platform: "lazada",
        userId: "user456",
        isPublic: true,
        bookmarkCount: 22,
        viewCount: 180,
      },
      {
        url: "https://shop.tiktok.com/product-6",
        title: "Skincare Set - Korean Beauty",
        description: "Complete 10-step Korean skincare routine",
        image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop",
        price: "89.99",
        originalPrice: "149.99",
        currency: "$",
        platform: "tiktok",
        userId: "user789",
        isPublic: true,
        bookmarkCount: 78,
        viewCount: 620,
      },
      {
        url: "https://shopee.sg/product-7",
        title: "Instant Air Fryer 6L",
        description: "Healthy cooking made easy",
        image: "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=400&h=400&fit=crop",
        price: "79.90",
        currency: "$",
        platform: "shopee",
        userId: "user123",
        isPublic: true,
        bookmarkCount: 45,
        viewCount: 380,
      },
      {
        url: "https://lazada.com/product-8",
        title: "Robot Vacuum Cleaner Smart Pro",
        description: "AI-powered cleaning with app control",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
        price: "299",
        originalPrice: "499",
        currency: "$",
        platform: "lazada",
        userId: "user456",
        isPublic: true,
        bookmarkCount: 31,
        viewCount: 260,
      },
    ];

    // Insert demo links
    for (const link of demoLinks) {
      await ctx.db.insert("links", link);
    }

    return null;
  },
}); 