import { mutation } from "./_generated/server";

export default mutation({
  args: {},
  handler: async (ctx) => {
    // Seed data with various types of links
    const links = [
      {
        url: "https://www.apple.com/iphone-15-pro/",
        title: "iPhone 15 Pro - Apple",
        description: "The most powerful iPhone ever. Titanium design with A17 Pro chip.",
        image: "https://www.apple.com/v/iphone-15-pro/a/images/overview/welcome/hero_endframe__ov6ewwmbhiqq_large.jpg",
        favicon: "https://www.apple.com/favicon.ico",
        price: "999",
        originalPrice: "1099",
        currency: "$",
        platform: "apple.com",
        userId: "demo_user",
        isPublic: true,
        bookmarkCount: 5,
        viewCount: 120,
      },
      {
        url: "https://store.steampowered.com/app/1245620/ELDEN_RING/",
        title: "ELDEN RING on Steam",
        description: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring.",
        image: "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
        favicon: "https://store.steampowered.com/favicon.ico",
        price: "59.99",
        originalPrice: "59.99",
        currency: "$",
        platform: "store.steampowered.com",
        userId: "demo_user",
        isPublic: true,
        bookmarkCount: 12,
        viewCount: 245,
      },
      {
        url: "https://www.goodreads.com/book/show/11127.The_Chronicles_of_Narnia",
        title: "The Chronicles of Narnia by C.S. Lewis",
        description: "The Chronicles of Narnia is a series of seven fantasy novels by C. S. Lewis.",
        image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1449868701i/11127.jpg",
        favicon: "https://www.goodreads.com/favicon.ico",
        platform: "goodreads.com",
        userId: "demo_user",
        isPublic: true,
        bookmarkCount: 8,
        viewCount: 156,
      },
      {
        url: "https://github.com/vercel/next.js",
        title: "vercel/next.js: The React Framework",
        description: "The React Framework for the Web. Used by some of the world's largest companies.",
        image: "https://repository-images.githubusercontent.com/70107786/6c5b7a00-5c7e-11eb-8f3e-1a4a7f9b9b7a",
        favicon: "https://github.com/favicon.ico",
        platform: "github.com",
        userId: "demo_user",
        isPublic: true,
        bookmarkCount: 25,
        viewCount: 512,
      },
      {
        url: "https://www.netflix.com/title/81040344",
        title: "Squid Game | Netflix Official Site",
        description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games.",
        image: "https://occ-0-2794-2219.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABbhSAVKKWvdCG5Cjp9cEIj7UqLqXcaKR2q3DlDVuFoZPKkjhBPiFCHYFMqXy5Lxa0YmNAQvfEye85g1SwM8gJ-M69gKW2xLKbVyl.jpg",
        favicon: "https://www.netflix.com/favicon.ico",
        platform: "netflix.com",
        userId: "demo_user",
        isPublic: true,
        bookmarkCount: 15,
        viewCount: 324,
      },
      {
        url: "https://www.airbnb.com/rooms/20951707",
        title: "Unique Cob Cottage - Airbnb",
        description: "Built from the earth, this unique cob cottage has a living grass roof and is situated in a quiet garden.",
        image: "https://a0.muscache.com/im/pictures/3a034e15-94d0-499b-b9a5-e8f0810a8f2e.jpg",
        favicon: "https://www.airbnb.com/favicon.ico",
        price: "85",
        currency: "$",
        platform: "airbnb.com",
        userId: "demo_user2",
        isPublic: true,
        bookmarkCount: 7,
        viewCount: 89,
      },
      {
        url: "https://www.coursera.org/learn/machine-learning",
        title: "Machine Learning | Coursera",
        description: "Master fundamental AI concepts and develop practical machine learning skills in this beginner-friendly program.",
        image: "https://s3.amazonaws.com/coursera_assets/meta_images/generated/XDP/XDP~COURSE!~machine-learning/XDP~COURSE!~machine-learning.jpeg",
        favicon: "https://www.coursera.org/favicon.ico",
        price: "49",
        currency: "$",
        platform: "coursera.org",
        userId: "demo_user2",
        isPublic: true,
        bookmarkCount: 18,
        viewCount: 267,
      },
      {
        url: "https://www.etsy.com/listing/731901671/",
        title: "Handmade Ceramic Coffee Mug - Etsy",
        description: "Beautiful handmade ceramic coffee mug with unique glaze patterns. Perfect for your morning coffee.",
        image: "https://i.etsystatic.com/15274110/r/il/7fd0d8/2885329037/il_1588xN.2885329037_1lmz.jpg",
        favicon: "https://www.etsy.com/favicon.ico",
        price: "28",
        originalPrice: "35",
        currency: "$",
        platform: "etsy.com",
        userId: "demo_user2",
        isPublic: true,
        bookmarkCount: 4,
        viewCount: 67,
      },
    ];

    // Insert all links
    for (const link of links) {
      await ctx.db.insert("links", link);
    }

    console.log("✅ Seed data inserted successfully");
  },
}); 